import {
  Activity,
  Bell,
  Camera,
  ChartNoAxesCombined,
  ClipboardList,
  Database,
  Download,
  Gauge,
  MonitorPlay,
  PlaySquare,
  Settings,
  Share2,
  ShieldCheck,
  UserCog,
  Users,
} from "lucide-react";

export const navigationItems = [
  { label: "Dashboard", href: "/dashboard", icon: Gauge },
  { label: "Live View", href: "/dashboard/live-view", icon: MonitorPlay },
  { label: "Playback", href: "/dashboard/playback", icon: PlaySquare },
  { label: "Cameras", href: "/dashboard/cameras", icon: Camera },
  { label: "Recordings", href: "/dashboard/recordings", icon: Database },
  { label: "Downloads", href: "/dashboard/downloads", icon: Download },
  { label: "Shared Videos", href: "/dashboard/shared-videos", icon: Share2 },
  { label: "Users", href: "/dashboard/users", icon: Users },
  { label: "Roles & Permissions", href: "/dashboard/roles", icon: ShieldCheck },
  { label: "Events", href: "/dashboard/events", icon: Activity },
  { label: "Analytics", href: "/dashboard/analytics", icon: ChartNoAxesCombined },
  { label: "Storage", href: "/dashboard/storage", icon: Database },
  { label: "Notifications", href: "/dashboard/notifications", icon: Bell },
  { label: "Audit Logs", href: "/dashboard/audit-logs", icon: ClipboardList },
  { label: "Settings", href: "/dashboard/settings", icon: Settings },
  { label: "Profile", href: "/dashboard/profile", icon: UserCog },
];

export const permissions = [
  "View Cameras",
  "Playback Videos",
  "Download Videos",
  "Share Videos",
  "Delete Videos",
  "Manage Users",
  "Manage Roles",
  "Manage Cameras",
  "Access Audit Logs",
  "Settings Access",
];
